export interface Company {
  id: number;
  name: string;
  nameKana: string;
  representative: string;
  email: string;
  status: boolean;
  address: string;
  createdAt: string;
  updatedAt: string;
  members: number;
}

export interface NewCompany {
  name: string;
  nameKana: string;
  representative: string;
  email: string;
  address: string;
  status: boolean;
}

export const dummyCompanies: Company[] = [
  {
    id: 1,
    name: "丸亀製麵",
    nameKana: "マルガメセイメン",
    representative: "代表者1",
    email: "abc1@marugameseimen.com",
    status: true,
    address: "東京都千代田区1-1-1",
    createdAt: "2025/09/14",
    updatedAt: "2025/09/14",
    members: 15,
  },
  {
    id: 2,
    name: "サントリー",
    nameKana: "サントリー",
    representative: "代表者2",
    email: "abc2@suntory.com",
    status: false,
    address: "大阪府大阪市2-2-2",
    createdAt: "2025/09/15",
    updatedAt: "2025/09/15",
    members: 8,
  },
  {
    id: 3,
    name: "任天堂",
    nameKana: "ニンテンドー",
    representative: "代表者3",
    email: "abc3@nintendo.com",
    status: true,
    address: "京都府京都市3-3-3",
    createdAt: "2025/09/16",
    updatedAt: "2025/09/16",
    members: 23,
  },
  {
    id: 4,
    name: "ソニー",
    nameKana: "ソニー",
    representative: "代表者4",
    email: "abc4@sony.com",
    status: true,
    address: "東京都港区4-4-4",
    createdAt: "2025/09/12",
    updatedAt: "2025/09/12",
    members: 30,
  },
  {
    id: 5,
    name: "パナソニック",
    nameKana: "パナソニック",
    representative: "代表者5",
    email: "abc5@panasonic.com",
    status: false,
    address: "大阪府門真市5-5-5",
    createdAt: "2025/09/11",
    updatedAt: "2025/09/11",
    members: 18,
  },
  {
    id: 6,
    name: "ホンダ",
    nameKana: "ホンダ",
    representative: "代表者6",
    email: "abc6@honda.com",
    status: true,
    address: "東京都港区6-6-6",
    createdAt: "2025/09/10",
    updatedAt: "2025/09/10",
    members: 12,
  },
  {
    id: 7,
    name: "トヨタ",
    nameKana: "トヨタ",
    representative: "代表者7",
    email: "abc7@toyota.com",
    status: true,
    address: "愛知県豊田市7-7-7",
    createdAt: "2025/09/09",
    updatedAt: "2025/09/09",
    members: 25,
  },
  {
    id: 8,
    name: "ソフトバンク",
    nameKana: "ソフトバンク",
    representative: "代表者8",
    email: "abc8@softbank.com",
    status: false,
    address: "東京都港区8-8-8",
    createdAt: "2025/09/08",
    updatedAt: "2025/09/08",
    members: 10,
  },
  {
    id: 9,
    name: "楽天",
    nameKana: "ラクテン",
    representative: "代表者9",
    email: "abc9@rakuten.com",
    status: true,
    address: "東京都世田谷区9-9-9",
    createdAt: "2025/09/07",
    updatedAt: "2025/09/07",
    members: 20,
  },
  {
    id: 10,
    name: "ファナック",
    nameKana: "ファナック",
    representative: "代表者10",
    email: "abc10@fanuc.com",
    status: true,
    address: "山梨県南都留郡10-10-10",
    createdAt: "2025/09/06",
    updatedAt: "2025/09/06",
    members: 14,
  },
  {
    id: 11,
    name: "日立",
    nameKana: "ヒタチ",
    representative: "代表者11",
    email: "abc11@hitachi.com",
    status: true,
    address: "東京都千代田区11-11-11",
    createdAt: "2025/09/05",
    updatedAt: "2025/09/05",
    members: 22,
  },
  {
    id: 12,
    name: "三菱電機",
    nameKana: "ミツビシデンキ",
    representative: "代表者12",
    email: "abc12@mitsubishielectric.com",
    status: false,
    address: "東京都千代田区12-12-12",
    createdAt: "2025/09/04",
    updatedAt: "2025/09/04",
    members: 16,
  },
  {
    id: 13,
    name: "富士通",
    nameKana: "フジツウ",
    representative: "代表者13",
    email: "abc13@fujitsu.com",
    status: true,
    address: "神奈川県川崎市13-13-13",
    createdAt: "2025/09/03",
    updatedAt: "2025/09/03",
    members: 28,
  },
  {
    id: 14,
    name: "リクルート",
    nameKana: "リクルート",
    representative: "代表者14",
    email: "abc14@recruit.com",
    status: true,
    address: "東京都千代田区14-14-14",
    createdAt: "2025/09/02",
    updatedAt: "2025/09/02",
    members: 9,
  },
  {
    id: 15,
    name: "セブンイレブン",
    nameKana: "セブンイレブン",
    representative: "代表者15",
    email: "abc15@seven-eleven.com",
    status: false,
    address: "東京都豊島区15-15-15",
    createdAt: "2025/09/01",
    updatedAt: "2025/09/01",
    members: 11,
  },
];
